# Generated by Django 5.0.3 on 2024-03-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anciennete',
            old_name='duree',
            new_name='en_cours',
        ),
    ]
